_wandb:
    value:
        cli_version: 0.21.0
        e:
            ddwbm46p5egiyna7d53esadf8jsazlix:
                args:
                    - --precision
                    - fp16
                    - --epochs
                    - "15"
                codePath: run_precision_experiment.py
                codePathLocal: run_precision_experiment.py
                email: qingliii@emails.bjut.edu.cn
                executable: /home/lu/miniconda3/envs/dl/bin/python
                git:
                    commit: b2bfd0d2f95bf908be918c2b79c8aaacad8dfd6d
                    remote: https://github.com/QingLiii/my_leaarning.git
                host: pop-os
                os: Linux-6.12.10-76061203-generic-x86_64-with-glibc2.35
                program: /home/lu/my_leaarning/run_precision_experiment.py
                python: CPython 3.9.23
                root: /home/lu/my_leaarning
                startedAt: "2025-07-13T16:35:42.844167Z"
                writerId: ddwbm46p5egiyna7d53esadf8jsazlix
        m: []
        python_version: 3.9.23
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.9.23
            "5": 0.21.0
            "10":
                - 20
            "12": 0.21.0
            "13": linux-x86_64
batch_size:
    value: 24
dataset:
    value: iu_xray
epochs:
    value: 15
experiment_type:
    value: precision_comparison
learning_rate_ed:
    value: 0.0001
learning_rate_ve:
    value: 5e-05
mixed_precision:
    value: fp16
model:
    value: R2Gen
optimizer:
    value: Adam
precision:
    value: fp16
scheduler:
    value: StepLR
system/cpu_count:
    value: 24
system/cuda_available:
    value: true
system/cuda_version:
    value: "12.1"
system/gpu_compute_capability:
    value: "8.9"
system/gpu_count:
    value: 1
system/gpu_memory_total_gb:
    value: 7.63092041015625
system/gpu_multiprocessor_count:
    value: 36
system/gpu_name:
    value: NVIDIA GeForce RTX 4070 Laptop GPU
system/memory_total_gb:
    value: 31.082626342773438
system/python_version:
    value: "3.9"
system/torch_version:
    value: 2.5.1
