_wandb:
    value:
        cli_version: 0.21.0
        e:
            xo2cmrjqxs4klu0ua4stefnxb10m27oc:
                codePath: quick_wandb_test.py
                codePathLocal: quick_wandb_test.py
                cpu_count: 16
                cpu_count_logical: 24
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "997466697728"
                        used: "80317915136"
                email: qingliii@emails.bjut.edu.cn
                executable: /home/lu/miniconda3/envs/dl/bin/python
                git:
                    commit: ecc118f212a51790c5a931fe6f9f68a1b1a45b30
                    remote: https://github.com/QingLiii/my_leaarning.git
                gpu: NVIDIA GeForce RTX 4070 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 4608
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4070 Laptop GPU
                      uuid: GPU-d7d2b5fd-d817-f2d6-35e4-d17d6b45c99c
                host: pop-os
                memory:
                    total: "33374715904"
                os: Linux-6.12.10-76061203-generic-x86_64-with-glibc2.35
                program: /home/lu/my_leaarning/quick_wandb_test.py
                python: CPython 3.9.23
                root: /home/lu/my_leaarning
                startedAt: "2025-07-13T15:07:55.023433Z"
                writerId: xo2cmrjqxs4klu0ua4stefnxb10m27oc
        m: []
        python_version: 3.9.23
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.9.23
            "5": 0.21.0
            "10":
                - 20
            "12": 0.21.0
            "13": linux-x86_64
batch_size:
    value: 4
learning_rate:
    value: 0.001
system/cpu_count:
    value: 24
system/cuda_available:
    value: true
system/cuda_version:
    value: "12.1"
system/gpu_count:
    value: 1
system/gpu_name:
    value: NVIDIA GeForce RTX 4070 Laptop GPU
system/memory_total_gb:
    value: 31.082626342773438
system/python_version:
    value: "3.9"
system/torch_version:
    value: 2.5.1
test_type:
    value: quick_verification
