_wandb:
    value:
        cli_version: 0.21.0
        e:
            7azzb2f5yfw7545mea6dd6b6udco033g:
                args:
                    - --epochs
                    - "20"
                    - --batch_size
                    - "12"
                codePath: train_mimic_cxr_fixed.py
                codePathLocal: train_mimic_cxr_fixed.py
                cpu_count: 16
                cpu_count_logical: 24
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "997466697728"
                        used: "97455026176"
                email: qingliii@emails.bjut.edu.cn
                executable: /home/lu/miniconda3/envs/dl/bin/python
                git:
                    commit: 4c481ed5a5aca108656fcdc427b2fa4610a6c133
                    remote: https://github.com/QingLiii/my_leaarning.git
                gpu: NVIDIA GeForce RTX 4070 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 4608
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4070 Laptop GPU
                      uuid: GPU-d7d2b5fd-d817-f2d6-35e4-d17d6b45c99c
                host: pop-os
                memory:
                    total: "33374711808"
                os: Linux-6.12.10-76061203-generic-x86_64-with-glibc2.35
                program: /home/lu/my_leaarning/train_mimic_cxr_fixed.py
                python: CPython 3.9.23
                root: /home/lu/my_leaarning
                startedAt: "2025-07-14T11:39:09.520335Z"
                writerId: 7azzb2f5yfw7545mea6dd6b6udco033g
        m: []
        python_version: 3.9.23
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 13
                - 15
                - 16
            "4": 3.9.23
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
batch_size:
    value: 12
beam_size:
    value: 3
d_model:
    value: 512
dataset:
    value: MIMIC-CXR
epochs:
    value: 20
gamma:
    value: 0.8
lr_ed:
    value: 0.0001
lr_ve:
    value: 5e-05
max_seq_length:
    value: 100
num_heads:
    value: 8
num_layers:
    value: 3
precision:
    value: FP32
seed:
    value: 456789
step_size:
    value: 1
