_wandb:
    value:
        cli_version: 0.21.0
        e:
            2r0p4v4ju6es2uwdfp8rhagfig5ufws4:
                args:
                    - --precision
                    - fp32
                    - --epochs
                    - "15"
                codePath: mixed_precision_trainer_fixed.py
                codePathLocal: mixed_precision_trainer_fixed.py
                cpu_count: 16
                cpu_count_logical: 24
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "997466697728"
                        used: "94245654528"
                email: qingliii@emails.bjut.edu.cn
                executable: /home/lu/miniconda3/envs/dl/bin/python
                git:
                    commit: 1bab4157f42768027fccf9eae7a1757ab7548060
                    remote: https://github.com/QingLiii/my_leaarning.git
                gpu: NVIDIA GeForce RTX 4070 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 4608
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4070 Laptop GPU
                      uuid: GPU-d7d2b5fd-d817-f2d6-35e4-d17d6b45c99c
                host: pop-os
                memory:
                    total: "33374711808"
                os: Linux-6.12.10-76061203-generic-x86_64-with-glibc2.35
                program: /home/lu/my_leaarning/mixed_precision_trainer_fixed.py
                python: CPython 3.9.23
                root: /home/lu/my_leaarning
                startedAt: "2025-07-14T06:22:30.856797Z"
                writerId: 2r0p4v4ju6es2uwdfp8rhagfig5ufws4
        m: []
        python_version: 3.9.23
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 1
                - 2
                - 13
                - 15
                - 16
            "4": 3.9.23
            "5": 0.21.0
            "10":
                - 20
            "12": 0.21.0
            "13": linux-x86_64
batch_size:
    value: 12
dataset:
    value: iu_xray
epochs:
    value: 15
gradient_accumulation_steps:
    value: 1
learning_rate_ed:
    value: 0.0001
learning_rate_ve:
    value: 5e-05
lr_scheduler:
    value: StepLR
max_seq_length:
    value: 60
mixed_precision:
    value: false
model_name:
    value: R2Gen
optimizer:
    value: Adam
seed:
    value: 9223
system/cpu_count:
    value: 24
system/cuda_available:
    value: true
system/cuda_version:
    value: "12.1"
system/gpu_compute_capability:
    value: "8.9"
system/gpu_count:
    value: 1
system/gpu_memory_total_gb:
    value: 7.63092041015625
system/gpu_multiprocessor_count:
    value: 36
system/gpu_name:
    value: NVIDIA GeForce RTX 4070 Laptop GPU
system/memory_total_gb:
    value: 31.082622528076172
system/python_version:
    value: "3.9"
system/torch_version:
    value: 2.5.1
threshold:
    value: 3
